name: Validate Commit Messages

on: push

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          # Get the latest commit message
          latest_commit_message=$(git log -1 --pretty=%B)

          # Check if the latest commit message matches the required pattern
          if ! [[ $latest_commit_message =~ ^(Breaking|Build|Chore|Docs|Fix|New|Update|WIP):\ ? ]]; then
            echo "Invalid commit message: $latest_commit_message"
            exit 1
          fi
