name: Validate Commit Messages

on: push

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          git log --format=%B ${{ github.event.before }}..${{ github.sha }} | while read -r line; do
            if ! [[ $line =~ ^[A-Z]+-[0-9]+: ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done
